# Generated by Django 4.1.3 on 2022-11-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='User',
            new_name='user',
        ),
    ]
